# Generated by Django 2.2 on 2020-04-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
